"""
claude-env :: Application - RAG Service - ContextPackGenerator
"""
from __future__ import annotations

import argparse
import json
import logging
import subprocess
from collections import Counter
from collections.abc import Callable
from pathlib import Path

from claudenv.domain.memory import MemoryType, NodeKind
from claudenv.ports import IMemoryGraph

logger = logging.getLogger(__name__)

LANG_BY_EXT = {
    ".py": "Python", ".ts": "TypeScript", ".tsx": "TypeScript", ".js": "JavaScript",
    ".jsx": "JavaScript", ".go": "Go", ".java": "Java", ".kt": "Kotlin",
    ".rs": "Rust", ".rb": "Ruby", ".cs": "C#", ".cpp": "C++", ".c": "C",
    ".swift": "Swift", ".sql": "SQL", ".sh": "Shell", ".zsh": "Shell",
    ".md": "Markdown", ".yaml": "YAML", ".yml": "YAML",
}
MARKER_OPEN = (
    "<!-- generated by claude-env context-pack; "
    "edits below the marker survive regeneration -->"
)


def _git_files(root: Path) -> list[str]:
    r = subprocess.run(
        ["git", "-C", str(root), "ls-files"],
        capture_output=True, text=True,
    )
    return [f for f in r.stdout.splitlines() if f] if r.returncode == 0 else []


def repo_shape(root: Path, files: list[str]) -> dict:
    langs = Counter()
    topdirs = Counter()
    for f in files:
        ext = Path(f).suffix
        if ext in LANG_BY_EXT:
            langs[LANG_BY_EXT[ext]] += 1
        topdirs[f.split("/")[0] if "/" in f else "(root)"] += 1
    return {"languages": langs.most_common(6),
            "top_dirs": topdirs.most_common(12),
            "file_count": len(files)}


def detect_commands(root: Path) -> list[tuple[str, str]]:
    """(purpose, command) pairs detected from project manifests."""
    cmds: list[tuple[str, str]] = []
    pkg = root / "package.json"
    if pkg.exists():
        try:
            scripts = (json.loads(pkg.read_text()).get("scripts") or {})
            for name in ("test", "build", "lint", "dev", "start", "typecheck"):
                if name in scripts:
                    cmds.append((name, f"npm run {name}"))
        except Exception:
            # malformed package.json — skip npm command detection, keep going.
            logger.debug("could not parse %s for scripts", pkg, exc_info=True)
    mk = root / "Makefile"
    if mk.exists():
        for line in mk.read_text(errors="ignore").splitlines():
            if line and not line.startswith(("\t", ".", "#")) and ":" in line:
                target = line.split(":", 1)[0].strip()
                if target in ("test", "build", "lint", "fmt", "run", "check"):
                    cmds.append((target, f"make {target}"))
    if (root / "pyproject.toml").exists() or (root / "requirements.txt").exists():
        if (root / "tests").is_dir() or (root / "test").is_dir():
            cmds.append(("test", "pytest"))
    if (root / "go.mod").exists():
        cmds.append(("test", "go test ./..."))
        cmds.append(("build", "go build ./..."))
    if (root / "Cargo.toml").exists():
        cmds.append(("test", "cargo test"))
        cmds.append(("build", "cargo build"))
    seen, out = set(), []
    for purpose, c in cmds:
        if c not in seen:
            seen.add(c)
            out.append((purpose, c))
    return out


class ContextPackGenerator:
    """Assemble a high-signal CLAUDE.md draft from what the platform knows.

    Pulls together:
      * repo shape       — languages, top-level layout, biggest modules (git)
      * commands         — detected from Makefile / package.json / pyproject /
                           requirements / go.mod / Cargo.toml
      * team conventions — procedural memory nodes (workflow/convention/pattern)
      * recent decisions — episodic decision nodes for this repo

    Output is written to CLAUDE.generated.md by default (never overwrites an
    existing CLAUDE.md unless --write --force), with generation markers so the
    nightly job can refresh it without touching hand-written content.
    """

    def __init__(
        self,
        memory_graph_factory: Callable[[str], IMemoryGraph] | None = None,
    ) -> None:
        # Factory builds a namespace-scoped IMemoryGraph (proj-<repo>, global).
        # When absent (e.g. DB not bootstrapped) the pack degrades gracefully and
        # is produced from repo signals alone.
        self._memory_graph_factory = memory_graph_factory

    def memory_sections(self, repo: str) -> tuple[list[dict], list[dict]]:
        """(conventions, decisions) from the memory graph; empty when none."""
        conventions, decisions = [], []
        if self._memory_graph_factory is None:
            return conventions, decisions
        try:
            for ns in (f"proj-{repo}", "global"):
                mgr = self._memory_graph_factory(ns)
                for n in mgr.list_nodes(
                    memory_type=MemoryType.PROCEDURAL, limit=20,
                ):
                    conventions.append({"name": n.name, "body": n.body})
                if ns.startswith("proj-"):
                    for n in mgr.list_nodes(
                        memory_type=MemoryType.EPISODIC, limit=40,
                    ):
                        if n.node_kind == NodeKind.DECISION:
                            decisions.append({
                                "name": n.name,
                                "updated": n.updated_at.isoformat()[:10],
                                "body": n.body,
                            })
        except Exception:
            # DB not bootstrapped yet — repo signals alone still produce a
            # useful pack, so degrade gracefully. Log in case it's a real fault.
            logger.info(
                "memory sections unavailable for repo %s; "
                "producing pack from repo signals only",
                repo, exc_info=True,
            )
        return conventions[:15], decisions[:10]

    def generate(self, root: Path) -> str:
        repo = root.name
        files = _git_files(root)
        shape = repo_shape(root, files)
        cmds = detect_commands(root)
        conventions, decisions = self.memory_sections(repo)

        L = [MARKER_OPEN, "", f"# {repo}", ""]
        langs = ", ".join(f"{name} ({n})" for name, n in shape["languages"])
        L += [f"{shape['file_count']} tracked files. Languages: {langs or 'n/a'}.", ""]

        L += ["## Layout", ""]
        for d, n in shape["top_dirs"]:
            L.append(f"- `{d}/` — {n} files" if d != "(root)" else f"- root — {n} files")
        L.append("")

        if cmds:
            L += ["## Commands", ""]
            for purpose, c in cmds:
                L.append(f"- {purpose}: `{c}`")
            L.append("")

        if conventions:
            L += ["## Conventions (from team memory)", ""]
            for c in conventions:
                detail = (c["body"].get("rule") or c["body"].get("desc")
                          or json.dumps(c["body"])[:100])
                L.append(f"- **{c['name']}** — {detail}")
            L.append("")

        if decisions:
            L += ["## Recent decisions (from team memory)", ""]
            for d in decisions:
                why = d["body"].get("why") or d["body"].get("reason") or ""
                L.append(f"- {d['updated']} **{d['name']}**"
                         + (f" — {why[:120]}" if why else ""))
            L.append("")

        L += ["## Notes", "",
              "- Retrieval, memory, and policy enforcement run locally via claude-env.",
              "- Regenerate this file: `claude-env context-pack . --write`", ""]
        return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate a CLAUDE.md context pack")
    ap.add_argument("repo_root")
    ap.add_argument("--write", action="store_true",
                    help="write CLAUDE.generated.md (or CLAUDE.md with --force)")
    ap.add_argument("--force", action="store_true",
                    help="with --write: write/overwrite CLAUDE.md itself")
    args = ap.parse_args()

    root = Path(args.repo_root).resolve()
    if not root.is_dir():
        print(f"not a directory: {root}")
        return 2
    content = ContextPackGenerator().generate(root)
    if not args.write:
        print(content)
        return 0
    target = root / ("CLAUDE.md" if args.force else "CLAUDE.generated.md")
    if (target.name == "CLAUDE.md" and target.exists()
            and MARKER_OPEN not in target.read_text(errors="ignore")):
        print(f"refusing to overwrite hand-written {target} "
              f"(no generation marker). Use CLAUDE.generated.md instead.")
        return 1
    target.write_text(content)
    print(f"context pack written -> {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
